### ISSUE TITLE
token

### ISSUE THREAD

**Issue by neeksor** [grod220/FB-eng-demo#1]
you might want to invalidate that token in accesstoken.txt.. 
![410b806c3f8e6bb8571c 1](https://user-images.githubusercontent.com/4803103/30679817-dd601a8e-9e50-11e7-9987-a7d1fdcf1bf3.png)

**Comment by grod220** [comment]
Ah! Thanks for alerting me. Not sure exactly where one can check it, but I've reset the app secret.

**Comment by neeksor** [comment]
The access token is still valid. You can check at: https://developers.facebook.com/tools/debug/accesstoken/
To invalidate the token you can remove the app from your account or change your password.

**Comment by grod220** [comment]
Thanks for that link! Sent a delete request using the graph api explorer.
